-- +goose Up
CREATE TABLE Users (
	Id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CreatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	Username TEXT NOT NULL UNIQUE CHECK (char_length(Username) >= 3)
);

-- +goose Down
DROP TABLE Users;
