-- +goose Up
CREATE TABLE World (
	Id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CreatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	Title TEXT NOT NULL,
	Thumbnail TEXT DEFAULT NULL,
	MapData JSONB DEFAULT '{}' NOT NULL
);

-- +goose Down
DROP TABLE World;
