package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"backend/graph/model"
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
)

// --- helpers ---

func jsonBytesToMap(data []byte) map[string]any {
	var m map[string]any
	_ = json.Unmarshal(data, &m)
	if m == nil {
		return map[string]any{}
	}
	return m
}

func mapToJSONBytes(m map[string]any) []byte {
	if m == nil {
		return []byte("{}")
	}
	b, _ := json.Marshal(m)
	return b
}

func int64PtrToStrPtr(i *int64) *string {
	if i == nil {
		return nil
	}
	s := strconv.FormatInt(*i, 10)
	return &s
}

func strPtrToInt64Ptr(s *string) (*int64, error) {
	if s == nil {
		return nil, nil
	}
	i, err := strconv.ParseInt(*s, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	return &i, nil
}

// --- mutations: users ---

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	var u model.User
	var id int64
	err := r.DB.QueryRowContext(ctx,
		`INSERT INTO Users (Username) VALUES ($1) RETURNING Id, CreatedAt, UpdatedAt, Username`,
		input.Username).
		Scan(&id, &u.CreatedAt, &u.UpdatedAt, &u.Username)
	if err != nil {
		return nil, err
	}
	u.ID = strconv.FormatInt(id, 10)
	return &u, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	intID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid id")
	}

	var u model.User
	var dbID int64
	err = r.DB.QueryRowContext(ctx,
		`UPDATE Users SET Username = $1, UpdatedAt = NOW() WHERE Id = $2 RETURNING Id, CreatedAt, UpdatedAt, Username`,
		input.Username, intID).
		Scan(&dbID, &u.CreatedAt, &u.UpdatedAt, &u.Username)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	u.ID = strconv.FormatInt(dbID, 10)
	return &u, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	intID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid id")
	}

	result, err := r.DB.ExecContext(ctx, `DELETE FROM Users WHERE Id = $1`, intID)
	if err != nil {
		return false, err
	}
	n, _ := result.RowsAffected()
	return n > 0, nil
}

// --- mutations: worlds ---

// CreateWorld is the resolver for the createWorld field.
func (r *mutationResolver) CreateWorld(ctx context.Context, input model.CreateWorldInput) (*model.World, error) {
	var w model.World
	var id int64
	var mapData []byte
	err := r.DB.QueryRowContext(ctx,
		`INSERT INTO World (Title, Thumbnail, MapData) VALUES ($1, $2, $3)
		 RETURNING Id, CreatedAt, UpdatedAt, Title, Thumbnail, MapData`,
		input.Title, input.Thumbnail, mapToJSONBytes(input.MapData)).
		Scan(&id, &w.CreatedAt, &w.UpdatedAt, &w.Title, &w.Thumbnail, &mapData)
	if err != nil {
		return nil, err
	}
	w.ID = strconv.FormatInt(id, 10)
	w.MapData = jsonBytesToMap(mapData)
	return &w, nil
}

// UpdateWorld is the resolver for the updateWorld field.
func (r *mutationResolver) UpdateWorld(ctx context.Context, id string, input model.UpdateWorldInput) (*model.World, error) {
	intID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid id")
	}

	var w model.World
	var dbID int64
	var mapData []byte
	err = r.DB.QueryRowContext(ctx,
		`UPDATE World SET Title = $1, Thumbnail = $2, MapData = $3, UpdatedAt = NOW()
		 WHERE Id = $4
		 RETURNING Id, CreatedAt, UpdatedAt, Title, Thumbnail, MapData`,
		input.Title, input.Thumbnail, mapToJSONBytes(input.MapData), intID).
		Scan(&dbID, &w.CreatedAt, &w.UpdatedAt, &w.Title, &w.Thumbnail, &mapData)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	w.ID = strconv.FormatInt(dbID, 10)
	w.MapData = jsonBytesToMap(mapData)
	return &w, nil
}

// DeleteWorld is the resolver for the deleteWorld field.
func (r *mutationResolver) DeleteWorld(ctx context.Context, id string) (bool, error) {
	intID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid id")
	}

	result, err := r.DB.ExecContext(ctx, `DELETE FROM World WHERE Id = $1`, intID)
	if err != nil {
		return false, err
	}
	n, _ := result.RowsAffected()
	return n > 0, nil
}

// --- mutations: map assets ---

// CreateMapAsset is the resolver for the createMapAsset field.
func (r *mutationResolver) CreateMapAsset(ctx context.Context, input model.CreateMapAssetInput) (*model.MapAsset, error) {
	worldID, err := strPtrToInt64Ptr(input.WorldID)
	if err != nil {
		return nil, err
	}

	var a model.MapAsset
	var id int64
	var dbWorldID *int64
	var data []byte
	err = r.DB.QueryRowContext(ctx,
		`INSERT INTO MapAsset (WorldId, Title, Type, Data) VALUES ($1, $2, $3, $4)
		 RETURNING Id, CreatedAt, UpdatedAt, WorldId, Title, Type, Data`,
		worldID, input.Title, input.Type, mapToJSONBytes(input.Data)).
		Scan(&id, &a.CreatedAt, &a.UpdatedAt, &dbWorldID, &a.Title, &a.Type, &data)
	if err != nil {
		return nil, err
	}
	a.ID = strconv.FormatInt(id, 10)
	a.WorldID = int64PtrToStrPtr(dbWorldID)
	a.Data = jsonBytesToMap(data)
	return &a, nil
}

// UpdateMapAsset is the resolver for the updateMapAsset field.
func (r *mutationResolver) UpdateMapAsset(ctx context.Context, id string, input model.UpdateMapAssetInput) (*model.MapAsset, error) {
	intID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid id")
	}

	worldID, err := strPtrToInt64Ptr(input.WorldID)
	if err != nil {
		return nil, err
	}

	var a model.MapAsset
	var dbID int64
	var dbWorldID *int64
	var data []byte
	err = r.DB.QueryRowContext(ctx,
		`UPDATE MapAsset SET WorldId = $1, Title = $2, Type = $3, Data = $4, UpdatedAt = NOW()
		 WHERE Id = $5
		 RETURNING Id, CreatedAt, UpdatedAt, WorldId, Title, Type, Data`,
		worldID, input.Title, input.Type, mapToJSONBytes(input.Data), intID).
		Scan(&dbID, &a.CreatedAt, &a.UpdatedAt, &dbWorldID, &a.Title, &a.Type, &data)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	a.ID = strconv.FormatInt(dbID, 10)
	a.WorldID = int64PtrToStrPtr(dbWorldID)
	a.Data = jsonBytesToMap(data)
	return &a, nil
}

// DeleteMapAsset is the resolver for the deleteMapAsset field.
func (r *mutationResolver) DeleteMapAsset(ctx context.Context, id string) (bool, error) {
	intID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid id")
	}

	result, err := r.DB.ExecContext(ctx, `DELETE FROM MapAsset WHERE Id = $1`, intID)
	if err != nil {
		return false, err
	}
	n, _ := result.RowsAffected()
	return n > 0, nil
}

// --- queries: users ---

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	rows, err := r.DB.QueryContext(ctx, `SELECT Id, CreatedAt, UpdatedAt, Username FROM Users ORDER BY Id`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var users []*model.User
	for rows.Next() {
		var u model.User
		var id int64
		if err := rows.Scan(&id, &u.CreatedAt, &u.UpdatedAt, &u.Username); err != nil {
			return nil, err
		}
		u.ID = strconv.FormatInt(id, 10)
		users = append(users, &u)
	}
	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	intID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid id")
	}

	var u model.User
	var dbID int64
	err = r.DB.QueryRowContext(ctx,
		`SELECT Id, CreatedAt, UpdatedAt, Username FROM Users WHERE Id = $1`, intID).
		Scan(&dbID, &u.CreatedAt, &u.UpdatedAt, &u.Username)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	u.ID = strconv.FormatInt(dbID, 10)
	return &u, nil
}

// --- queries: worlds ---

// Worlds is the resolver for the worlds field.
func (r *queryResolver) Worlds(ctx context.Context) ([]*model.World, error) {
	rows, err := r.DB.QueryContext(ctx,
		`SELECT Id, CreatedAt, UpdatedAt, Title, Thumbnail, MapData FROM World ORDER BY Id`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var worlds []*model.World
	for rows.Next() {
		var w model.World
		var id int64
		var mapData []byte
		if err := rows.Scan(&id, &w.CreatedAt, &w.UpdatedAt, &w.Title, &w.Thumbnail, &mapData); err != nil {
			return nil, err
		}
		w.ID = strconv.FormatInt(id, 10)
		w.MapData = jsonBytesToMap(mapData)
		worlds = append(worlds, &w)
	}
	return worlds, nil
}

// World is the resolver for the world field.
func (r *queryResolver) World(ctx context.Context, id string) (*model.World, error) {
	intID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid id")
	}

	var w model.World
	var dbID int64
	var mapData []byte
	err = r.DB.QueryRowContext(ctx,
		`SELECT Id, CreatedAt, UpdatedAt, Title, Thumbnail, MapData FROM World WHERE Id = $1`, intID).
		Scan(&dbID, &w.CreatedAt, &w.UpdatedAt, &w.Title, &w.Thumbnail, &mapData)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	w.ID = strconv.FormatInt(dbID, 10)
	w.MapData = jsonBytesToMap(mapData)
	return &w, nil
}

// --- queries: map assets ---

// MapAssets is the resolver for the mapAssets field.
func (r *queryResolver) MapAssets(ctx context.Context) ([]*model.MapAsset, error) {
	rows, err := r.DB.QueryContext(ctx,
		`SELECT Id, CreatedAt, UpdatedAt, WorldId, Title, Type, Data FROM MapAsset ORDER BY Id`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var assets []*model.MapAsset
	for rows.Next() {
		var a model.MapAsset
		var id int64
		var dbWorldID *int64
		var data []byte
		if err := rows.Scan(&id, &a.CreatedAt, &a.UpdatedAt, &dbWorldID, &a.Title, &a.Type, &data); err != nil {
			return nil, err
		}
		a.ID = strconv.FormatInt(id, 10)
		a.WorldID = int64PtrToStrPtr(dbWorldID)
		a.Data = jsonBytesToMap(data)
		assets = append(assets, &a)
	}
	return assets, nil
}

// MapAsset is the resolver for the mapAsset field.
func (r *queryResolver) MapAsset(ctx context.Context, id string) (*model.MapAsset, error) {
	intID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid id")
	}

	var a model.MapAsset
	var dbID int64
	var dbWorldID *int64
	var data []byte
	err = r.DB.QueryRowContext(ctx,
		`SELECT Id, CreatedAt, UpdatedAt, WorldId, Title, Type, Data FROM MapAsset WHERE Id = $1`, intID).
		Scan(&dbID, &a.CreatedAt, &a.UpdatedAt, &dbWorldID, &a.Title, &a.Type, &data)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	a.ID = strconv.FormatInt(dbID, 10)
	a.WorldID = int64PtrToStrPtr(dbWorldID)
	a.Data = jsonBytesToMap(data)
	return &a, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
