// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateMapAssetInput struct {
	WorldID *string        `json:"worldId,omitempty"`
	Title   string         `json:"title"`
	Type    string         `json:"type"`
	Data    map[string]any `json:"data,omitempty"`
}

type CreateUserInput struct {
	Username string `json:"username"`
}

type CreateWorldInput struct {
	Title     string         `json:"title"`
	Thumbnail *string        `json:"thumbnail,omitempty"`
	MapData   map[string]any `json:"mapData,omitempty"`
}

type MapAsset struct {
	ID        string         `json:"id"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	WorldID   *string        `json:"worldId,omitempty"`
	Title     string         `json:"title"`
	Type      string         `json:"type"`
	Data      map[string]any `json:"data"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateMapAssetInput struct {
	WorldID *string        `json:"worldId,omitempty"`
	Title   string         `json:"title"`
	Type    string         `json:"type"`
	Data    map[string]any `json:"data,omitempty"`
}

type UpdateUserInput struct {
	Username string `json:"username"`
}

type UpdateWorldInput struct {
	Title     string         `json:"title"`
	Thumbnail *string        `json:"thumbnail,omitempty"`
	MapData   map[string]any `json:"mapData,omitempty"`
}

type User struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Username  string    `json:"username"`
}

type World struct {
	ID        string         `json:"id"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	Title     string         `json:"title"`
	Thumbnail *string        `json:"thumbnail,omitempty"`
	MapData   map[string]any `json:"mapData"`
}
